@hostname = http://localhost
@port = 3000
@baseUrl = {{hostname}}:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2M5M2QxMWNlYjQ0MGQ5M2Y0MzE1MTAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzQxMzg0OTl9.LhsQVeHa3GyA8D7e6-VNkVUEFFz6pYHUpbzgbyHKHxg

# Categories

### List styles by category
GET {{baseUrl}}/api/categories/1/styles HTTP/1.1

### GET categories
GET {{baseUrl}}/api/categories HTTP/1.1
