@hostname = http://localhost
@port = 3000
@baseUrl = {{hostname}}:{{port}}

# Styles

### List styles
GET {{baseUrl}}/api/styles HTTP/1.1

### GET style by id
GET {{baseUrl}}/api/styles/1 HTTP/1.1

# ### POST style
# POST {{baseUrl}}/api/styles HTTP/1.1
# content-type: application/json
# x-auth-token: {{token}}

# {"name":"Fantasy Wild"}

# ### UPDATE style
# PUT {{baseUrl}}/api/styles/1 HTTP/1.1
# content-type: application/json

# {"name":"Holrdayland"}

# ### DELETE style
# DELETE {{baseUrl}}/api/styles/1 HTTP/1.1
# x-auth-token: {{token}}
